#ifndef APS2_ENUMS_H_
#define APS2_ENUMS_H_

// SEQUENCER MODES
enum APS2_TRIGGER_SOURCE {EXTERNAL=0, INTERNAL, SOFTWARE, SYSTEM};

enum APS2_RUN_MODE {RUN_SEQUENCE=0, TRIG_WAVEFORM, CW_WAVEFORM};

enum APS2_RUN_STATE {STOPPED=0, PLAYING};

enum APS2_HOST_TYPE {APS=0, TDM};

enum APS2_BITFILE_STORAGE_MEDIA {
	BITFILE_MEDIA_DRAM,
	BITFILE_MEDIA_EPROM
};

#endif
