#ifndef APS2_ENUMS_H_
#define APS2_ENUMS_H_

// SEQUENCER MODES
typedef enum {EXTERNAL=0, INTERNAL, SOFTWARE} TRIGGER_SOURCE;

typedef enum {RUN_SEQUENCE=0, TRIG_WAVEFORM, CW_WAVEFORM} RUN_MODE;

typedef enum {STOPPED=0, PLAYING} RUN_STATE;

#endif