#ifndef APS2_ENUMS_H_
#define APS2_ENUMS_H_

// SEQUENCER MODES
enum TRIGGER_SOURCE {EXTERNAL=0, INTERNAL, SOFTWARE};

enum RUN_MODE {RUN_SEQUENCE=0, TRIG_WAVEFORM, CW_WAVEFORM};

enum RUN_STATE {STOPPED=0, PLAYING};

#endif
