version: 1.2.{build}-{branch}
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\libaps2

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
platform:
  - x64
configuration:
  - Release

# scripts that run after cloning repository
install:
  # HDF5
  - ps: Invoke-WebRequest "https://support.hdfgroup.org/ftp/HDF5/current18/bin/windows/extra/hdf5-1.8.18-win64-vs2015-shared.zip" -OutFile hdf5.zip
  - 7z x hdf5.zip -y
  - ps: Start-Process -FilePath msiexec -ArgumentList '/I "hdf5\HDF5-1.8.18-win64.msi" /quiet' -Wait

build:
  parallel: true # enable MSBuild parallel builds
  project: c:\projects\libaps2\build\ALL_BUILD.vcxproj      # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal

# scripts to run before build
before_build:
  - cd c:\projects\libaps2
  - md build
  - cd build
  - set HDF5_DIR=C:/Program Files/HDF_Group/HDF5/1.8.18/cmake
  - cmake -G "Visual Studio 14 2015 Win64" ..\src

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
# build_script:

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

# artifacts:
#
#   # pushing a single file
#   - path: test.zip
#
#   # pushing a single file with environment variable in path and "Deployment name" specified
#   - path: MyProject\bin\$(configuration)
#     name: myapp
#
#   # pushing entire folder as a zip archive
#   - path: logs
#
#     # Deploy to GitHub Releases
#   - provider: GitHub
#     artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
#     draft: false
#     prerelease: false
#     on:
#       branch: master                # release from master branch only
#       appveyor_repo_tag: true       # deploy on tag push only
#
#
# scripts to run before deployment
before_deploy:

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
#deploy: off
