version: 1.2.{build}-{branch}
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
skip_non_tags: false

# Build worker image (VM template)
image: Visual Studio 2015
environment:
  matrix:
    - generator: "MinGW Makefiles"
      dialect: mingw
    - generator: "MinGW Makefiles"
      dialect: mingw-w64

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\libaps2

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
platform:
  - x64
configuration:
  - Release

# scripts that run after cloning repository
install:
  # get dependencies
  - git submodule update --init --recursive

build: off

# scripts to run before build
before_build:
  - if "%dialect%"=="mingw" set PATH=c:\MinGW\bin;%PATH%
  - if "%dialect%"=="mingw-w64" set PATH=c:\msys64\mingw64\bin;%PATH%

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  # create build directory and call cmake
  - md build
  - cd build
  - cmake -H. -Bbuild -G"%generator%" -DCMAKE_BUILD_TYPE=%configuration%
  - cmake --build . --config %configuration%


# artifacts configuration
artifacts:

  # pushing entire folder as a zip archive
  - path: build\Release

#
#     # Deploy to GitHub Releases
#   - provider: GitHub
#     artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
#     draft: false
#     prerelease: false
#     on:
#       branch: master                # release from master branch only
#       appveyor_repo_tag: true       # deploy on tag push only
#
