config:
  AWGDir: C:\Users\qlab\Documents\AWG
  KernelDir: C:\Users\qlab\Documents\Kernels
  LogDir: C:\Users\qlab\Documents\
  PulsePrimitivesLibrary: all90
  cnot_implementation: CNOT_CR
  PlotBackground: '#EAEAF2'
  GridColor: white


qubits:
  q1:
    measure:
      AWG: BBNAPS1 12
      trigger: BBNAPS1 12m2
      receiver: q1-DemodSS
      generator: AutodyneM1
      autodyne_freq: 10e6
      pulse_params:
        amp: 0.5 
        cutoff: 2.0
        length: 3e-6 
        shape_fun: tanh
        sigma: 5e-9
      gain: -9 # dB
    control:
      AWG: BBNAPS2 12
      generator: q1source
      frequency: 70.4e6
      pulse_params:
        cutoff: 2.0
        length: 150e-9
        pi2Amp: 0.1773  
        piAmp: 0.35417 
        shape_fun: drag
        drag_scaling: 0
        sigma: 5.0e-09
      gain: -10 # dB

instruments: !include C:\Users\qlab\Documents\Config\instruments.yml
filters: !include C:\Users\qlab\Documents\Config\filters.yml

markers:
  mark_M3: BBNAPS2 12m3
